'use client';

export const GET_POC = 'GET_POC';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const OPEN_SIGNUP_APPLY_FLOW = 'OPEN_SIGNUP_APPLY_FLOW';
export const UPDATE_HRDATA_TO_APPLY = 'UPDATE_HRDATA_TO_APPLY';
export const PUSH_TAILOR_TO_LOGGING_USER = 'PUSH_TAILOR_TO_LOGGING_USER';
export const CLOSE_SIGNUP_APPLY_FLOW = 'CLOSE_SIGNUP_APPLY_FLOW';
export const SET_TOUCHPOINT_DATA = 'SET_TOUCHPOINT_DATA';
export const MODIFY_APPLY_DATA = 'MODIFY_APPLY_DATA';
export const ON_APPLY_STEP_STARTED = 'ON_APPLY_STEP_STARTED';
export const UPDATE_WORK_CONTROL = 'UPDATE_WORK_CONTROL';
export const TOGGLE_AGGREGATOR_FLOW = 'TOGGLE_AGGREGATOR_FLOW';
export const TOGGLE_ASK_APPLIED = 'TOGGLE_ASK_APPLIED';
export const SET_OUTREACH_DATA = 'SET_OUTREACH_DATA';

export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAN_SLATE = 'CLEAN_SLATE';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const SET_BULK_ERRORS = 'SET_BULK_ERRORS';
export const REMOVE_BULK_ERRORS = 'REMOVE_BULK_ERRORS';
export const SET_SUCCESS = 'SET_SUCCESS';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';

export const TOGGLE_MANAGE_PREFERENCES_MODAL = 'TOGGLE_MANAGE_PREFERENCES_MODAL';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_MASTERS = 'SET_MASTERS';
export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const SET_LOADER = 'SET_LOADER';
export const SET_ME_LOADER = 'SET_ME_LOADER';
export const SET_DOWNLOAD_TAILOR_RESUME_LOADER = 'SET_DOWNLOAD_TAILOR_RESUME_LOADER'

export const SET_PROFILE_PERCENT = 'SET_PROFILE_PERCENT';
export const SET_PROFILE_REM_PERCENT = 'SET_PROFILE_REM_PERCENT';

export const SET_VIDEO_RESUME = 'SET_VIDEO_RESUME';

export const SET_PROFILE_STATE = 'SET_PROFILE_STATE';
export const REMOVE_PROFILE_STATE = 'REMOVE_PROFILE_STATE';

export const SET_TALENT_PREFERENCES = 'SET_TALENT_PREFERENCES';

export const SET_JOB_FUNCTION_MASTER = 'SET_JOB_FUNCTION_MASTER';

export const REMOVE_SINGLE_LOCK = 'REMOVE_SINGLE_LOCK';
export const REMOVE_NESTED_LOCK = 'REMOVE_NESTED_LOCK';

export const SET_OPP_MASTER = 'SET_OPP_MASTER';
export const SET_OPP_READY_FILTERS = 'SET_OPP_READY_FILTERS';
export const UPDATE_ALL_OPP_FILTERS = 'UPDATE_ALL_OPP_FILTERS';
export const ADD_SIMILAR_JOBS = 'ADD_SIMILAR_JOBS';

export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';
export const UPDATE_MASTER_DATA = 'UPDATE_MASTER_DATA';
export const SET_SINGLEHR_REDIRECT = 'SET_SINGLEHR_REDIRECT';

export const SET_FORCE_REGISTRATION = 'SET_FORCE_REGISTRATION';

export const VR_PUSHER_TOGGLE = 'VR_PUSHER_TOGGLE';
export const VR_PUSHER_SUBSCRIBE = 'VR_PUSHER_SUBSCRIBE';
export const SET_TNC_MODAL = 'SET_TNC_MODAL';
export const SET_SIDEBAR_COLLAPSE = 'SET_SIDEBAR_COLLAPSE';
export const SET_SIDEBAR_RESUME_REVIEW_CLICKED='SET_SIDEBAR_RESUME_REVIEW_CLICKED'
export const SET_LEGAL_MASTER = 'SET_LEGAL_MASTER';
export const SET_NOTIFY_SUCCESS = 'SET_NOTIFY_SUCCESS';

export const SET_PERMISSION_DATA = 'SET_PERMISSION_DATA';
export const SET_DEVICE_INFO = 'SET_DEVICE_INFO';
export const RESET_PERMISSION_DATA = 'RESET_PERMISSION_DATA';

export const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR'
export const REMOVE_NETWORK_ERROR = 'REMOVE_NETWORK_ERROR'

export const ALL_OPP_MASTER_VALUE = 'ALL_OPP_MASTER_VALUE'


export const HR_UPDATE_NEEDED = 'HR_UPDATE_NEEDED';
export const HR_UPDATE_COMPLETED = 'HR_UPDATE_COMPLETED';
export const SET_ALL_JOBS = 'SET_ALL_JOBS';


export const SET_BOOKMARK_COUNT = 'SET_BOOKMARK_COUNT';
export const SET_BOOKMARK_SIMILAR_JOBS = 'SET_BOOKMARK_SIMILAR_JOBS';
export const SET_HR_COMPANY_DETAILS = 'SET_HR_COMPANY_DETAILS';
export const SET_TRIGGER_ALL_JOBS_RESET = 'SET_TRIGGER_ALL_JOBS_RESET';


export const RESET_TRANSFORM_LOADER = 'RESET_TRANSFORM_LOADER';
export const SET_RESUME_HEALTH_CONTROL = 'SET_RESUME_HEALTH_CONTROL';
export const SET_RESUME_TRANSFORM = 'SET_RESUME_TRANSFORM';
export const SET_RESUME_DASHBOARD = 'SET_RESUME_DASHBOARD';
export const SET_RESUME_HEALTH_REPORTS = 'SET_RESUME_HEALTH_REPORTS';
export const SET_ACTIVE_TRANSFORMATION = 'SET_ACTIVE_TRANSFORMATION';
export const SET_TRANSFORM_DONE_MODAL = 'SET_TRANSFORM_DONE_MODAL';
export const UPDATE_TRANSFORM_DONE_VIEWED = 'UPDATE_TRANSFORM_DONE_VIEWED';
export const UPDATE_HEALTH_REPORT_TRANSFORM_VIEWED = 'UPDATE_HEALTH_REPORT_TRANSFORM_VIEWED';
export const UPDATE_RESUME_DASHBOARD_TRANSFORM_VIEWED = 'UPDATE_RESUME_DASHBOARD_TRANSFORM_VIEWED';
export const SET_OPENAI_DOWN_MODAL = 'SET_OPENAI_DOWN_MODAL';
export const SET_HEALTH_CHECK_SOCKET_LOADER = 'SET_HEALTH_CHECK_SOCKET_LOADER';
export const SET_BG_RESUME_HEALTH_CHECK_ID = 'SET_BG_RESUME_HEALTH_CHECK_ID';

export const SET_TAILOR_MODAL_OPEN = 'SET_TAILOR_MODAL_OPEN';
export const SET_TRANSFORMED_RESUME_MODAL_OPEN = 'SET_TRANSFORMED_RESUME_MODAL_OPEN';
export const RESET_TRANSFORMED_RESUME_MODAL='RESET_TRANSFORMED_RESUME_MODAL';
export const SEED_TRANSFORMED_RESUME = 'SEED_TRANSFORMED_RESUME';
export const RESET_TAILOR_FOR_NEW_JOB = 'RESET_TAILOR_FOR_NEW_JOB';
export const SEED_TAILOR = 'SEED_TAILOR';
export const SET_TAILOR_JSON = 'SET_TAILOR_JSON';
export const SET_CONFIG_JSON = 'SET_CONFIG_JSON';
export const SET_SORTING_JSON = 'SET_SORTING_JSON';
export const SET_TAILOR_RESUME_DOWNLOADED = 'SET_TAILOR_RESUME_DOWNLOADED';
export const REMOVE_EDITOR_SECTION = 'REMOVE_EDITOR_SECTION';
export const SET_REPORT_JSON = 'SET_REPORT_JSON';
export const SET_EXPANDED_SECTION = 'SET_EXPANDED_SECTION';
export const SET_TAILOR_DASHBOARD_RESUME = 'SET_TAILOR_DASHBOARD_RESUME';
export const SET_SELECTED_RESUME = 'SET_SELECTED_RESUME';

export const HAPPPY_AGENT_SET_LOADING = 'HAPPPY_AGENT_SET_LOADING';
export const HAPPPY_AGENT_SET = 'HAPPPY_AGENT_SET';
export const HAPPPY_AGENT_FAILED = 'HAPPPY_AGENT_FAILED';
export const HAPPPY_AGENT_RESET = 'HAPPPY_AGENT_RESET';
export const HAPPPY_AGENT_DAILY_LIMIT_SET = 'HAPPPY_AGENT_DAILY_LIMIT_SET';
export const HAPPPY_AGENT_DAILY_USED_INCREMENT = 'HAPPPY_AGENT_DAILY_USED_INCREMENT';

/* Next.js only: restores the persisted session after mount, because the auth
 * reducer can no longer read localStorage while the module is evaluating. */
export const HYDRATE_AUTH = 'HYDRATE_AUTH';


